<a href="https://colab.research.google.com/github/Kalyani6301/192210159-TOC/blob/main/datascienceipynb.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#  1.Problem 1In a cricket tournament, based on the outcome of a particular match a team gets following points:wins gets 7 pointsdraws gets 2 points losses gets pointsTeam Aravali plays 8 matches in this tournament. It wins 4 matches, loses 3 matches and draws 1. What is the total number of points gained by the Team austria?

#a.The outcome variables are defined below?

#b.Calculate the total points gained by Team Austria and print.



In [ ]:
# a)the account variables are defined below
#define outcome variables
win=4
draw=1
loss=3




In [ ]:
#define points tables of cricket
winning_points=7
draw_points=2
loss_points=0

In [ ]:
#b)total points gained by team austria
total_points=(win*winning_points+draw*draw_points+loss*loss_points)
print(total_points)

30


In [2]:
#Problem 2

#Root of a function f(x) is defined as the value x where f(x)=0 Consider a quadratic function f(x)=x2+3x-4 where f(x)=0

#Find the value of the function f(x) at points x=7, x=-1,x=1

#a)Calculate the value of f the function f(x) f(x) at x=2.

#b) Calculate the value of the function f(x) at x = 1

In [3]:
#define the quadratic equation
def f(x):
  return x**2+3*x-4

In [4]:
#value of the function at the points x=7,x=-1,x=1.
value_of_x_seven=f(7)
value_of_x_minus_one=f(-1)
value_of_x_one=f(1)


In [5]:
_#value of function f(x)at x=2
value_of_x_two=f(2)

In [6]:
#value of function f(x)at x=1
value_of_x_one=f(1)

In [7]:
print(value_of_x_two)
print(value_of_x_one)


6
0


In [16]:
#problem 3""""A list contains the averagw daily temperature (in degree Celsius) of a ciy over a particular week. Write a Python code to swap the highest and the lowest temperatures
#a) A list containing average daily temperature over a week temperatures = [34, 40, 29, 33, 42, 37, 39 ]

#b) The expected output

#c) Store the highest temperature

#d) Index of the element with the highest temperature max_temp_index =

#e) Store the lowest temperature min_temp =

#f) Index of the element with the lowest temperature min_temp_index =

In [17]:
#list containing average daily temperature over a week temperature = [34,40,29,33,42,37,39]
temperatures = [34,40,29,33,42,37,39]


In [25]:
#c) store the highest temperature
max_temp = max(temperatures)


In [26]:
#d) index of the element with the highest temperature
max_temp_index = temperatures.index(max_temp)


In [27]:
#e) store the lowest temperature
min_temp =min(temperatures)


In [28]:
#f) index of the element with the lowest temperature
min_temp_index =temperatures.index(min_temp)



In [29]:
#print the result of all
print(temperatures)
print(max_temp)
print(max_temp_index)
print(min_temp)
print(min_temp_index)

[34, 40, 29, 33, 42, 37, 39]
42
4
29
2


In [30]:
#PROBLEM 4 calculate the median price

#a) Step 1 - Obtain th sorted list

#b) Check if the number of elements in the list is even or odd

#c) Use the corresponding formula to calculate the median and print the median

#d) Check which is greater, mean or median


In [32]:
#given list of prices

prices = [67, 65, 78, 24, 11, 80, 55, 30]

print('original list is:',prices)



original list is: [67, 65, 78, 24, 11, 80, 55, 30]


In [33]:
#  Sort the list
sorted_prices = sorted(prices)


In [34]:
#Check if the number of elements is even or odd
num_prices = len(sorted_prices)
is_even = num_prices % 2 == 0


In [41]:
#Calculate the median
if is_even:
    median=(sorted_prices[num_prices//2-1] + sorted_prices[num_prices//2])/2
else:
    median=sorted_prices[num_prices//2]
    #  Print the median
print("Median price:", median)
    # Calculate mean
mean=sum(sorted_prices)/num_prices



Median price: 60.0


In [42]:
#Check which is greater, mean or median
if mean > median:
    print("Mean is greater than median.")
elif median > mean:
    print("Median is greater than mean.")
else:
    print("Mean and median are equal.")

Median is greater than mean.


In [57]:
#problem 5

#Having a nested list sometines might be a bit problematic. An individual was asked to collect the names of companies in the technology sector. While creating the list, by mistake the last three companies were subsumed in a list as shown below. You are required to get rid of the nexting


In [78]:
#a) The list of tech companies accurated by the individual tech_companies ['Qualcomm', 'Google', 'Apple',['Nvidia','Cisco','Samsung']]


In [48]:
tech_companies = ['Qualcomm', 'Google', 'Apple', ['Nvidia', 'Cisco', 'Samsung']]


In [49]:
# Flatten the nested list
flattened_tech_companies = [company if isinstance(company, str) else company for sublist in tech_companies for company in sublist]



In [50]:
# Print the flattened list
print(flattened_tech_companies)

['Q', 'u', 'a', 'l', 'c', 'o', 'm', 'm', 'G', 'o', 'o', 'g', 'l', 'e', 'A', 'p', 'p', 'l', 'e', 'Nvidia', 'Cisco', 'Samsung']


In [53]:
#Problem 6

#Another measure of average Mode is defined as the value that appears most often in a set of data values. Mode corresponds to the most frequent value. You are given a list of numbers and you need to calculate the node of this list.

#A list containing average daily temperature over 10 days.
temperatures = 134, 40, 29, 29, 33, 42, 40, 39, 34, 34,331


In [64]:
from statistics import mode
temperatures = [134, 40, 29, 29, 33, 42, 40, 39, 34, 34, 331]




In [65]:
# Calculate the mode
mode_value = mode(temperatures)

In [66]:

# Print the mode
print("Mode:", mode_value)

Mode: 40


In [79]:
#Problem 7 numpy
#Construct a 2-d 10a^-10 matrix with the following constraints:
#The element at [0,0] should be 1
#The element at [0,9] should be 100
#The element at [9,0]should be 50
#The interval between elements in rows should be constant
#The interval between elements in columns should be constant



In [83]:
import numpy as np
# Define the constraints
a = 10
start_value = 1
end_value_row = 100
end_value_col = 50
num_rows = 10
num_cols = 10


In [84]:
# Calculate the common ratio for the geometric progression
common_ratio_row = (end_value_row / start_value) ** (1 / (num_cols - 1))
common_ratio_col = (end_value_col / start_value) ** (1 / (num_rows - 1))

In [85]:
# Create the 2D matrix
matrix = np.zeros((num_rows, num_cols))

In [86]:
for i in range(num_rows):
    for j in range(num_cols):
        matrix[i, j] = start_value * (common_ratio_row ** j) * (common_ratio_col ** i)


In [87]:
# Print the resulting matrix
print(matrix)

[[1.00000000e+00 1.66810054e+00 2.78255940e+00 4.64158883e+00
  7.74263683e+00 1.29154967e+01 2.15443469e+01 3.59381366e+01
  5.99484250e+01 1.00000000e+02]
 [1.54445210e+00 2.57630139e+00 4.29752973e+00 7.16871164e+00
  1.19581317e+01 1.99473660e+01 3.32742119e+01 5.55047308e+01
  9.25874712e+01 1.54445210e+02]
 [2.38533230e+00 3.97897410e+00 6.63732883e+00 1.10717318e+01
  1.84687617e+01 3.08077514e+01 5.13904266e+01 8.57243983e+01
  1.42996915e+02 2.38533230e+02]
 [3.68403150e+00 6.14533492e+00 1.02510365e+01 1.70997595e+01
  2.85241180e+01 4.75810965e+01 7.93700526e+01 1.32397227e+02
  2.20851886e+02 3.68403150e+02]
 [5.68981020e+00 9.49117546e+00 1.58322349e+01 2.64097595e+01
  4.40541340e+01 7.34867246e+01 1.22583245e+02 2.04481177e+02
  3.41095160e+02 5.68981020e+02]
 [8.78763934e+00 1.46586659e+01 2.44521285e+01 4.07886087e+01
  6.80395000e+01 1.13496727e+02 1.89323950e+02 3.15811383e+02
  5.26805138e+02 8.78763934e+02]
 [1.35720881e+01 2.26396074e+01 3.77651413e+01 6.29960525e

In [88]:
#problem 8 numpy
#Construct a list of first 100 natural numbers.Create a two dimensional array with 10 rows and whose each row contains 10 columns and each number in this array is the square of the number from your constructed list.
 #For example [[1,4,9......,100] [121,144......]..........]

In [89]:
import numpy as np

# Construct a list of first 100 natural numbers
natural_numbers = np.arange(1, 101)




In [90]:
# Reshape the list into a two-dimensional array with 10 rows and 10 columns
two_dimensional_array = natural_numbers.reshape(10, 10)



In [91]:
# Square each element in the array
squared_array = np.square(two_dimensional_array)



In [92]:
# Print the resulting array
print(squared_array)

[[    1     4     9    16    25    36    49    64    81   100]
 [  121   144   169   196   225   256   289   324   361   400]
 [  441   484   529   576   625   676   729   784   841   900]
 [  961  1024  1089  1156  1225  1296  1369  1444  1521  1600]
 [ 1681  1764  1849  1936  2025  2116  2209  2304  2401  2500]
 [ 2601  2704  2809  2916  3025  3136  3249  3364  3481  3600]
 [ 3721  3844  3969  4096  4225  4356  4489  4624  4761  4900]
 [ 5041  5184  5329  5476  5625  5776  5929  6084  6241  6400]
 [ 6561  6724  6889  7056  7225  7396  7569  7744  7921  8100]
 [ 8281  8464  8649  8836  9025  9216  9409  9604  9801 10000]]
